import type { Metadata } from "next";
import NavBar from "./components/ui/navbar";
import Footer from "./components/ui/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Novomon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <NavBar/>

      <body>
        {children}
      </body>

      <Footer/>
    </html>
  );
}
